# .mega-linter.yml

# Linter selection
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SEMGREP
  - REPOSITORY_SECRETLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
  - TSX_ESLINT
  - ENV_DOTENV_LINTER
  - JSON_NPM_PACKAGE_JSON_LINT